export const Actiontypes = {
    IS_USER_AUTHINTCATED:"IS_USER_AUTHINTCATED",
    organization:"organization",
    // REGISTER_USER:"REGISTER_USER"
    GET_USER_ROLES:"GET_USER_ROLES",
    GET_VALIDATED_USER_DETAILS:'GET_VALIDATED_USER_DETAILS',
}